### ISSUE TITLE
Review

### ISSUE THREAD

**Issue by llun** [llun/fake-classname-loader#1]
Need some reviews @shiawuen @tongrhj 😆

**Comment by shiawuen** [comment]
Seems to work eh, similar to what you did for the other app?

**Comment by llun** [comment]
@shiawuen yes but now with component name :D

**Comment by shiawuen** [comment]
Good job 😇

**Comment by shiawuen** [comment]
With this, do you still need `BABEL_DISABLE_CACHE=1`?

**Comment by llun** [comment]
For css no, but js, I think ava still need it.

**Comment by shiawuen** [comment]
Seem still required…else it will prompt on possible of caching errors.

**Comment by shiawuen** [comment]
👍
